language: node_js
sudo: false
node_js:
- node
branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/
before_install: 
- yarn global add greenkeeper-lockfile@1
install:
- yarn install
before_script:
- yarn build
- greenkeeper-lockfile-update
script:
- yarn test
after_script: 
- greenkeeper-lockfile-upload
deploy:
  skip_cleanup: true
  provider: npm
  email: adam@kreczko-lenner.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: master
    repo: adamkl/cloud-foundry-config-client
